<?php

use Drupal\user_welcome\Form\UserWelcomeForm;

/**
* Implements hook_preprocess_region
*/

function user_welcome_preprocess_page(&$variables)
{
    if ($variables['page']['sidebar_first']) {
        // Invalidate the cache on the user context, so we don't get old login data
        $variables['#cache']['contexts'][] = 'user';
        $user = Drupal\user\Entity\User::load(Drupal::currentUser()->id());
        $content = '';
        if (Drupal::currentUser()->isAuthenticated()) {
            $content  = '<p>Hello ' . $user->get('name')->value . '!<br>';
            $content .= 'Your last log in was ' . date('F jS, Y g:i a', $user->getLastLoginTime()) . '<br>';
            $content .= '<a href="/user/' . $user->id . '">Visit your profile</a>';
        }
        $config = Drupal::config(UserWelcomeForm::$CONFIG_NAME);
        if ($config->get('displayMessage')) {
            $content .= '<p>' . $config->get('message') . '</p>';
        }
        $variables['page']['sidebar_first'][]['#markup'] = $content;
    }
}