user_welcome.settings:
  type: config_object
  label: 'User Welcome Settings'
  mapping:
    user_welcome:
      message:
        type: text
        label: 'Message for all users:'
      displayMessage:
        type: checkbox
        label: 'Display custom message:'